services:
  _defaults:
    public: true
    autowire: true

  HeimrichHannot\BannerPlusBundle\:
    resource: '../../{Asset,EventListener}/*'
    autoconfigure: true

  HeimrichHannot\BannerPlusBundle\Type\HtmlType: ~